# Generated by Django 5.2.4 on 2025-10-29 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('guide', 'Text Guide'), ('image', 'Image'), ('video', 'Video'), ('link', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, help_text='For PDFs, images, and videos', null=True, upload_to='resources/')),
                ('content', models.TextField(blank=True, help_text='For text guides, write your guide content here')),
                ('external_url', models.URLField(blank=True, help_text='For external links (Google Drive, YouTube, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
