# Generated by Django 5.2.4 on 2025-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='content',
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('video', 'Video'), ('link', 'External Link')], max_length=10),
        ),
    ]
