# Generated by Django 5.2.4 on 2025-11-13 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_content_field'),
        ('communityowner_panel', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='community',
            field=models.ForeignKey(blank=True, help_text='If selected, only members of this community can see this resource. Leave empty for all communities.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='communityowner_panel.communityprofile'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='For PDFs, images, videos, and documents', null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('video', 'Video'), ('link', 'External Link'), ('document', 'Document (.txt, .csv)')], max_length=10),
        ),
    ]
