# Generated by Django 5.2.4 on 2025-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_resource_community_alter_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'External Link'), ('document', 'Document (.pdf, .txt, .csv, .xlsx, .xls)')], max_length=10),
        ),
    ]
