# Generated by Django 5.2.4 on 2025-11-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_convert_existing_pdf_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'External Link'), ('document', 'Document')], max_length=10),
        ),
    ]
