# Generated by Django 5.2.4 on 2025-11-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_update_document_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='For PDFs, images, videos, and documents (stored in Dropbox)', null=True, upload_to='resources/'),
        ),
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When to start showing this announcement')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing (leave blank for no end date)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Announcement',
                'verbose_name_plural': 'Platform Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the tip', max_length=200)),
                ('content', models.TextField(help_text='Safety tip content')),
                ('is_active', models.BooleanField(default=True, help_text='Show this tip to users')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_safety_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Tip',
                'verbose_name_plural': 'Safety Tips',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
