# Generated by Django 5.2.4 on 2025-11-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_resource_file_platformannouncement_safetytip'),
        ('communityowner_panel', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Platform Announcement', 'verbose_name_plural': 'Platform Announcements'},
        ),
        migrations.RemoveField(
            model_name='platformannouncement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='platformannouncement',
            name='priority',
        ),
        migrations.AddField(
            model_name='platformannouncement',
            name='community',
            field=models.ForeignKey(blank=True, help_text='If selected, only members of this community can see this announcement. Leave empty for all communities.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='communityowner_panel.communityprofile'),
        ),
        migrations.AddField(
            model_name='platformannouncement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the announcement (stored in Dropbox)', null=True, upload_to='announcements/'),
        ),
    ]
