# Generated by Django 5.2.4 on 2025-11-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_platformannouncement_options_and_more'),
        ('communityowner_panel', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetytip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Safety Tip', 'verbose_name_plural': 'Safety Tips'},
        ),
        migrations.RemoveField(
            model_name='safetytip',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='safetytip',
            name='order',
        ),
        migrations.RemoveField(
            model_name='safetytip',
            name='title',
        ),
        migrations.AddField(
            model_name='safetytip',
            name='community',
            field=models.ForeignKey(blank=True, help_text='If selected, only members of this community can see this tip. Leave empty for all communities.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_tips', to='communityowner_panel.communityprofile'),
        ),
    ]
