# Generated by Django 5.2.4 on 2025-10-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='priority',
        ),
    ]
