# Generated by Django 5.2.4 on 2025-10-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_panel', '0002_remove_priority_and_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
