# Generated by Django 5.2.4 on 2025-07-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_alter_user_community_user_city_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='community',
        ),
    ]
