# Generated by Django 5.2.4 on 2025-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_locked_user_last_attempt_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('login_attempts', models.IntegerField(default=0)),
                ('last_attempt_time', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IP login attempt',
                'verbose_name_plural': 'IP login attempts',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_attempt_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_attempts',
        ),
    ]
