# Generated by Django 5.2.4 on 2025-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_iploginattempt_remove_user_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
