# Generated by Django 5.2.4 on 2025-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='accounts/static/accounts/images/profile.png', upload_to='profile_pictures/'),
        ),
    ]
