# Generated by Django 5.2.4 on 2025-08-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_address_user_block_user_lot_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='A short bio or description about yourself'),
        ),
    ]
