# Generated by Django 5.2.4 on 2025-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('communityowner', 'Community Owner'), ('security', 'Security'), ('admin', 'Admin')], default='resident', max_length=20),
        ),
    ]
