# Generated by Django 5.2.4 on 2025-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('resident', 'Resident'), ('communityowner', 'Community Owner'), ('security', 'Security'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
