# Generated by Django 5.2.4 on 2025-10-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_profile_picture_url_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.district')),
            ],
            options={
                'verbose_name': 'location emergency contact',
                'verbose_name_plural': 'location emergency contacts',
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', False), ('district__isnull', True)), models.Q(('city__isnull', True), ('district__isnull', False)), _connector='OR'), name='location_emergency_contact_city_or_district')],
            },
        ),
    ]
