# Generated by Django 5.2.4 on 2025-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_locationemergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('resident', 'Resident'), ('communityowner', 'Community Owner'), ('security', 'Security'), ('admin', 'Admin')], default='resident', max_length=20),
        ),
    ]
