# Generated by Django 5.2.4 on 2025-11-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_sound_enabled',
            field=models.BooleanField(default=True, help_text='Enable notification sound'),
        ),
    ]
