# Generated by Django 5.2.4 on 2025-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_notification_sound_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('resident', 'Resident'), ('communityowner', 'Community President'), ('security', 'Security'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
