# Generated by Django 5.2.4 on 2025-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Enable notification bubbles/badges for messages and communications'),
        ),
    ]
