# Generated by Django 5.2.4 on 2025-11-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_receive_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationemergencycontact',
            options={'ordering': ['id'], 'verbose_name': 'location emergency contact', 'verbose_name_plural': 'location emergency contacts'},
        ),
        migrations.RemoveField(
            model_name='locationemergencycontact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='locationemergencycontact',
            name='order',
        ),
    ]
