# Generated by Django 5.2.4 on 2025-11-13 12:04

from django.db import migrations


def delete_contacts_without_district(apps, schema_editor):
    """Delete all emergency contacts that don't have a district assigned"""
    LocationEmergencyContact = apps.get_model('accounts', 'LocationEmergencyContact')
    contacts_to_delete = LocationEmergencyContact.objects.filter(district__isnull=True)
    count = contacts_to_delete.count()
    contacts_to_delete.delete()
    print(f"Deleted {count} emergency contact(s) without district")


def reverse_delete_contacts(apps, schema_editor):
    """Reverse operation - nothing to do since we can't restore deleted records"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_order_and_is_active_from_location_emergency_contact'),
    ]

    operations = [
        migrations.RunPython(delete_contacts_without_district, reverse_delete_contacts),
    ]
