# Generated by Django 5.2.4 on 2025-11-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_delete_contacts_without_district'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationemergencycontact',
            name='location_emergency_contact_city_or_district',
        ),
        migrations.RemoveField(
            model_name='locationemergencycontact',
            name='city',
        ),
        migrations.AlterField(
            model_name='locationemergencycontact',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.district'),
        ),
    ]
