# Generated by Django 5.2.4 on 2025-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='original_roles',
            field=models.JSONField(blank=True, default=dict, help_text='Stores original roles before expiry'),
        ),
    ]
