# Generated by Django 5.2.4 on 2025-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_panel', '0002_subscription_original_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='data_deletion_date',
            field=models.DateTimeField(blank=True, help_text='When data should be deleted (1 month after trial expiry)', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Whether this is a free trial subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_expired_at',
            field=models.DateTimeField(blank=True, help_text='When the trial expired', null=True),
        ),
    ]
