# Generated by Django 5.2.4 on 2025-08-03 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '0001_initial'),
    ]

    # 0001 already created Post, PostReply, PostShare, PostReaction.
    # This migration duplicates those CreateModel operations and causes
    # `relation ... already exists` errors on PostgreSQL. Make this a no-op.
    operations = []
