# Generated by Django 5.2.4 on 2025-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20250803_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreply',
            name='id',
        ),
        migrations.AddField(
            model_name='postreply',
            name='reply_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
