# Generated by Django 5.2.4 on 2025-08-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_remove_postreply_id_postreply_reply_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_panel.post')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
