# Generated by Django 5.2.4 on 2025-08-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='post_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='user_panel.post')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
