# Generated by Django 5.2.4 on 2025-08-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_postvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_url',
        ),
        migrations.DeleteModel(
            name='PostVideo',
        ),
    ]
