# Generated by Django 5.2.4 on 2025-08-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0006_remove_post_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostShare',
        ),
    ]
