# Generated by Django 5.2.4 on 2025-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
