# Generated by Django 5.2.4 on 2025-10-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0009_postimage_image_url_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
