# Generated by Django 5.2.4 on 2025-10-25 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communityowner_panel', '0004_emergencycontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15)),
                ('target_type', models.CharField(choices=[('resident', 'Resident'), ('outsider', 'Non-Resident')], max_length=10)),
                ('target_description', models.TextField(blank=True, help_text='Description of non-resident target')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reasons', models.JSONField(default=list, help_text='List of selected reasons for the report')),
                ('details', models.TextField(blank=True, help_text='Additional details provided by reporter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('security_notes', models.TextField(blank=True, help_text='Internal notes by security personnel')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to='communityowner_panel.communityprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Report',
                'verbose_name_plural': 'Security Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
