# Generated by Django 5.2.4 on 2025-10-26 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityowner_panel', '0004_emergencycontact'),
        ('security_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('suspicious_activity', 'Suspicious Activity'), ('security_breach', 'Security Breach'), ('vandalism', 'Vandalism'), ('theft', 'Theft'), ('disturbance', 'Disturbance'), ('other', 'Other')], default='suspicious_activity', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='reported', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Specific location within community', max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('security_notes', models.TextField(blank=True, help_text='Notes from security personnel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='communityowner_panel.communityprofile')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('security_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_incident', to='security_panel.securityreport')),
            ],
            options={
                'verbose_name': 'Public Incident',
                'verbose_name_plural': 'Public Incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
