# Generated by Django 5.2.4 on 2025-10-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0002_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='pending', max_length=15),
        ),
    ]
