# Generated by Django 5.2.4 on 2025-10-26 07:40

from django.db import migrations


def update_status_values(apps, schema_editor):
    """Update existing status values to match new choices"""
    SecurityReport = apps.get_model('security_panel', 'SecurityReport')
    Incident = apps.get_model('security_panel', 'Incident')
    
    # Update SecurityReport status values
    status_mapping = {
        'new': 'pending',
        'investigating': 'investigating',
        'resolved': 'resolved',
        'closed': 'false_alarm',  # Map closed to false_alarm
    }
    
    for old_status, new_status in status_mapping.items():
        SecurityReport.objects.filter(status=old_status).update(status=new_status)
        Incident.objects.filter(status=old_status).update(status=new_status)


def reverse_status_values(apps, schema_editor):
    """Reverse the status value updates"""
    SecurityReport = apps.get_model('security_panel', 'SecurityReport')
    Incident = apps.get_model('security_panel', 'Incident')
    
    # Reverse mapping
    reverse_mapping = {
        'pending': 'new',
        'investigating': 'investigating',
        'resolved': 'resolved',
        'false_alarm': 'closed',
    }
    
    for new_status, old_status in reverse_mapping.items():
        SecurityReport.objects.filter(status=new_status).update(status=old_status)
        Incident.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0003_alter_incident_status_alter_securityreport_status'),
    ]

    operations = [
        migrations.RunPython(update_status_values, reverse_status_values),
    ]
