# Generated by Django 5.2.4 on 2025-10-27 11:37

from django.db import migrations


def update_unknown_person_text(apps, schema_editor):
    """Update existing reports to remove 'Unknown person' text"""
    SecurityReport = apps.get_model('security_panel', 'SecurityReport')
    
    # Update subject field
    reports_with_unknown = SecurityReport.objects.filter(
        subject__icontains='Unknown person'
    )
    
    for report in reports_with_unknown:
        # Replace "Unknown person" with empty string in subject
        report.subject = report.subject.replace(' / Unknown person', '').replace('/ Unknown person', '').replace('Unknown person', '')
        report.save(update_fields=['subject'])
    
    print(f"Updated {reports_with_unknown.count()} reports with 'Unknown person' in subject")


def reverse_update_unknown_person_text(apps, schema_editor):
    """Reverse migration - add back 'Unknown person' text"""
    SecurityReport = apps.get_model('security_panel', 'SecurityReport')
    
    # This is a one-way migration, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0004_auto_20251026_1540'),
    ]

    operations = [
        migrations.RunPython(
            update_unknown_person_text,
            reverse_update_unknown_person_text,
        ),
    ]
