# Generated by Django 5.2.4 on 2025-11-02 18:18

from django.db import migrations, models


def migrate_priority_values(apps, schema_editor):
    """Convert old priority values to new level-based values"""
    SecurityReport = apps.get_model('security_panel', 'SecurityReport')
    
    # Map old priorities to new levels
    # Note: 'high' and 'urgent' both map to 'level_3' (most serious)
    priority_mapping = {
        'low': 'level_1',
        'medium': 'level_2',
        'high': 'level_3',
        'urgent': 'level_3',  # Both high and urgent become level 3
    }
    
    # Update all existing records
    for old_priority, new_priority in priority_mapping.items():
        SecurityReport.objects.filter(priority=old_priority).update(priority=new_priority)


def reverse_migrate_priority_values(apps, schema_editor):
    """Reverse migration: convert level-based values back to old priorities"""
    SecurityReport = apps.get_model('security_panel', 'SecurityReport')
    
    # Map new levels back to old priorities
    # Note: level_3 maps back to 'high' (we can't distinguish between high and urgent)
    priority_mapping = {
        'level_1': 'low',
        'level_2': 'medium',
        'level_3': 'high',  # Default to 'high' for reverse migration
    }
    
    # Update all existing records
    for new_priority, old_priority in priority_mapping.items():
        SecurityReport.objects.filter(priority=new_priority).update(priority=old_priority)


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0005_auto_20251027_1937'),
    ]

    operations = [
        # Data migration: convert existing priority values
        migrations.RunPython(migrate_priority_values, reverse_migrate_priority_values),
        # Schema migration: update field choices
        migrations.AlterField(
            model_name='securityreport',
            name='priority',
            field=models.CharField(choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], default='level_2', max_length=10),
        ),
    ]
