# Generated by Django 5.2.4 on 2025-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0006_change_priority_to_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityreport',
            name='target_description',
        ),
        migrations.AddField(
            model_name='securityreport',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the incident happened', max_length=200),
        ),
    ]
