# Generated by Django 5.2.4 on 2025-11-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0007_remove_target_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityreport',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='securityreport',
            name='reporter_email',
        ),
        migrations.RemoveField(
            model_name='securityreport',
            name='security_notes',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='security_notes',
        ),
    ]
