# Generated by Django 5.2.4 on 2025-11-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0008_remove_unused_fields'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the security_notes column from both security_panel_securityreport and security_panel_incident tables
            sql=[
                "ALTER TABLE security_panel_securityreport DROP COLUMN IF EXISTS security_notes;",
                "ALTER TABLE security_panel_incident DROP COLUMN IF EXISTS security_notes;",
            ],
            reverse_sql=[
                # Reverse: Add the column back (if needed for rollback)
                "ALTER TABLE security_panel_securityreport ADD COLUMN security_notes TEXT;",
                "ALTER TABLE security_panel_incident ADD COLUMN security_notes TEXT;",
            ]
        ),
    ]
