# Generated by Django 5.2.4 on 2025-11-27 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityowner_panel', '0004_emergencycontact'),
        ('security_panel', '0009_remove_security_notes_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(help_text='Name of the visitor', max_length=200)),
                ('id_image', models.ImageField(blank=True, help_text="Photo of visitor's ID", null=True, upload_to='visitor_ids/')),
                ('status', models.CharField(choices=[('visiting', 'Currently Visiting'), ('returned', 'Returned Home')], default='visiting', max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True, help_text='When the visitor entered')),
                ('exit_time', models.DateTimeField(blank=True, help_text='When the visitor returned home/exited', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the visitor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='communityowner_panel.communityprofile')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_visitors', to=settings.AUTH_USER_MODEL)),
                ('visiting_resident', models.ForeignKey(help_text='Resident that the visitor is visiting', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-entry_time'],
            },
        ),
    ]
