# Generated by Django 5.2.4 on 2025-11-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_panel', '0010_visitorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='notes',
        ),
    ]
