# Generated by Django 5.2.4 on 2025-10-19 14:26

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityowner_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='communityprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('community_name'), name='uniq_lower_community_name'),
        ),
    ]
