# Generated by Django 5.2.4 on 2025-10-20 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityowner_panel', '0002_communityprofile_uniq_lower_community_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communityowner_panel.communityprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'community membership',
                'verbose_name_plural': 'community memberships',
            },
        ),
    ]
